name: Evaluate Best Model

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache conda packages
        uses: actions/cache@v4
        with:
          path: |
            ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Set up Conda (miniforge)
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          use-mamba: true
          activate-environment: permeability_torch
          environment-file: environment.yml
          auto-activate-base: false
          pkgs-dirs: ~/conda_pkgs_dir

      - name: Show environment info
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python --version
          which python

      - name: Run Evaluation
        shell: bash -l {0}
        run: |
          python -m script.evaluate